name: mtg-panel

services:
  mtg-panel:
    build: .
    container_name: mtg-panel
    restart: unless-stopped
    ports:
      - "3000:3000" # Добавляем обратно для локального доступа и отладки
    volumes:
      - ./data:/data
      - ./ssh_keys:/ssh_keys:ro
    environment:
      - PORT=3000
      - DATA_DIR=/data
      - AUTH_TOKEN=${AUTH_TOKEN}
      - AGENT_TOKEN=${AGENT_TOKEN}

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data

volumes:
  caddy_data:
